import enum

class ActionEnum(enum.Enum):
    READ = "READ"
    DELETE = "DELETE"
    UPDATE = "UPDATE"
    CREATE = "CREATE"

class ResourceEnum(enum.Enum):
    PRODUCT = "PRODUCT"
    ORDER = "ORDER"
    CUSTOMER = "CUSTOMER"
    CART = "CART"
    ADDRESS = "ADDRESS"
    INVOICE = "INVOICE"
    EMPLOYEE = "EMPLOYEE"
    ROLE = "ROLE"
    ROUTES = "ROUTES"
    SITE_CONFIG = "SITE_CONFIG"
    CATEGORY = "CATEGORY"
    ACTION = "ACTION"
    PERMISSION = "PERMISSION"
    STATISTICS = "STATISTICS"
    OTP = "OTP"

class OrderState(enum.Enum):
    ORDER_PLACED = "ORDER_PLACED"
    IN_PROGRESS = "IN_PROGRESS"
    DISPATCHED = "DISPATCHED"
    DELIVERED = "DELIVERED"
    ORDER_COLLECTED = "ORDER_COLLECTED"

class BusinessSector(enum.Enum):
    AGRICULTURE = "AGRICULTURE"
    CONSTRUCTION = "CONSTRUCTION"
    EDUCATION = "EDUCATION"
    FINANCE = "FINANCE"
    HEALTH = "HEALTH"
    HOSPITALITY = "HOSPITALITY"
    IT = "IT"
    MANUFACTURING = "MANUFACTURING"
    OTHER = "OTHER"
    RETAIL = "RETAIL"
    TECHNOLOGY = "TECHNOLOGY"
    TOURISM = "TOURISM"
    TRANSPORTATION = "TRANSPORTATION"

class TenantStatus(enum.Enum):
    TRIAL = "TRIAL"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    CANCELLED = "CANCELLED"

class ModuleEnum(enum.Enum):
    CUSTOM_ROLES = "CUSTOM_ROLES"
    STATISTICS = "STATISTICS"
    NAVIGATION = "NAVIGATION"
