"""init

Revision ID: 0d292653cf11
Revises: 
Create Date: 2026-02-06 16:32:56.263850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d292653cf11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('name', sa.Enum('READ', 'DELETE', 'UPDATE', 'CREATE', name='actionenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('addresses',
    sa.Column('addressId', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postCode', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('streetName', sa.String(), nullable=True),
    sa.Column('streetNumber', sa.String(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('addressId')
    )
    op.create_index(op.f('ix_addresses_postCode'), 'addresses', ['postCode'], unique=False)
    op.create_table('categories',
    sa.Column('categoryId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('imagePath', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('categoryId'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modules',
    sa.Column('name', sa.Enum('CUSTOM_ROLES', 'STATISTICS', 'NAVIGATION', name='moduleenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priceCents', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('resources',
    sa.Column('name', sa.Enum('PRODUCT', 'ORDER', 'CUSTOMER', 'CART', 'ADDRESS', 'INVOICE', 'EMPLOYEE', 'ROLE', 'ROUTES', 'SITE_CONFIG', 'CATEGORY', 'ACTION', 'PERMISSION', 'STATISTICS', 'OTP', name='resourceenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('routes',
    sa.Column('routeId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('routeId')
    )
    op.create_table('tenant_data',
    sa.Column('tenantId', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='tenantstatus'), nullable=True),
    sa.Column('trialStartedAt', sa.DateTime(), nullable=True),
    sa.Column('trialEndsAt', sa.DateTime(), nullable=True),
    sa.Column('billingCustomerId', sa.String(), nullable=True),
    sa.Column('maxEmployees', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tenantId')
    )
    op.create_table('customers',
    sa.Column('customerId', sa.String(), nullable=False),
    sa.Column('customerReference', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('companyNumber', sa.String(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('signedUp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('avatarPath', sa.String(), nullable=True),
    sa.Column('addressId', sa.String(), nullable=True),
    sa.Column('businessSector', sa.Enum('AGRICULTURE', 'CONSTRUCTION', 'EDUCATION', 'FINANCE', 'HEALTH', 'HOSPITALITY', 'IT', 'MANUFACTURING', 'OTHER', 'RETAIL', 'TECHNOLOGY', 'TOURISM', 'TRANSPORTATION', name='businesssector'), nullable=True),
    sa.ForeignKeyConstraint(['addressId'], ['addresses.addressId'], ),
    sa.PrimaryKeyConstraint('customerId')
    )
    op.create_index(op.f('ix_customers_customerReference'), 'customers', ['customerReference'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_lastName'), 'customers', ['lastName'], unique=False)
    op.create_table('employees',
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('superAdmin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('employeeId')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_lastName'), 'employees', ['lastName'], unique=False)
    op.create_table('enabled_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('moduleName', sa.Enum('CUSTOM_ROLES', 'STATISTICS', 'NAVIGATION', name='moduleenum'), nullable=True),
    sa.Column('enabledAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moduleName'], ['modules.name'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['tenant_data.tenantId'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('permissions',
    sa.Column('permissionId', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('READ', 'DELETE', 'UPDATE', 'CREATE', name='actionenum'), nullable=True),
    sa.Column('resource', sa.Enum('PRODUCT', 'ORDER', 'CUSTOMER', 'CART', 'ADDRESS', 'INVOICE', 'EMPLOYEE', 'ROLE', 'ROUTES', 'SITE_CONFIG', 'CATEGORY', 'ACTION', 'PERMISSION', 'STATISTICS', 'OTP', name='resourceenum'), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('permissionId')
    )
    op.create_table('products',
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagePath', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('categoryId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('resourceActions',
    sa.Column('action', sa.Enum('READ', 'DELETE', 'UPDATE', 'CREATE', name='actionenum'), nullable=False),
    sa.Column('resource', sa.Enum('PRODUCT', 'ORDER', 'CUSTOMER', 'CART', 'ADDRESS', 'INVOICE', 'EMPLOYEE', 'ROLE', 'ROUTES', 'SITE_CONFIG', 'CATEGORY', 'ACTION', 'PERMISSION', 'STATISTICS', 'OTP', name='resourceenum'), nullable=False),
    sa.ForeignKeyConstraint(['action'], ['actions.name'], ),
    sa.ForeignKeyConstraint(['resource'], ['resources.name'], ),
    sa.PrimaryKeyConstraint('action', 'resource')
    )
    op.create_table('site_configs',
    sa.Column('siteConfigId', sa.String(), nullable=False),
    sa.Column('tenantId', sa.String(), nullable=True),
    sa.Column('companyName', sa.String(), nullable=False),
    sa.Column('logoPath', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('companyNumber', sa.String(), nullable=True),
    sa.Column('addressId', sa.String(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressId'], ['addresses.addressId'], ),
    sa.ForeignKeyConstraint(['tenantId'], ['tenant_data.tenantId'], ),
    sa.PrimaryKeyConstraint('siteConfigId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tenantId')
    )
    op.create_table('carts',
    sa.Column('cartId', sa.String(), nullable=False),
    sa.Column('customerReference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerReference'], ['customers.customerReference'], ),
    sa.PrimaryKeyConstraint('cartId'),
    sa.UniqueConstraint('customerReference')
    )
    op.create_table('customerHistory',
    sa.Column('historyId', sa.String(), nullable=False),
    sa.Column('customerReference', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('companyNumber', sa.String(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('signedUp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('avatarPath', sa.String(), nullable=True),
    sa.Column('addressId', sa.String(), nullable=True),
    sa.Column('businessSector', sa.Enum('AGRICULTURE', 'CONSTRUCTION', 'EDUCATION', 'FINANCE', 'HEALTH', 'HOSPITALITY', 'IT', 'MANUFACTURING', 'OTHER', 'RETAIL', 'TECHNOLOGY', 'TOURISM', 'TRANSPORTATION', name='businesssector'), nullable=True),
    sa.ForeignKeyConstraint(['customerReference'], ['customers.customerReference'], ),
    sa.PrimaryKeyConstraint('historyId')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('customerReference', sa.Integer(), nullable=True),
    sa.Column('orderDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deliveryDate', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('orderState', sa.Enum('ORDER_PLACED', 'IN_PROGRESS', 'DISPATCHED', 'DELIVERED', 'ORDER_COLLECTED', name='orderstate'), nullable=True),
    sa.Column('selfCollect', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customerReference'], ['customers.customerReference'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_index(op.f('ix_orders_customerReference'), 'orders', ['customerReference'], unique=False)
    op.create_index(op.f('ix_orders_orderDate'), 'orders', ['orderDate'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('employeeId', sa.String(), nullable=True),
    sa.Column('expiresAt', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.employeeId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('productHistory',
    sa.Column('historyId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagePath', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('categoryId', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], ),
    sa.PrimaryKeyConstraint('historyId')
    )
    op.create_table('cartsProducts',
    sa.Column('cartId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartId'], ['carts.cartId'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], ),
    sa.PrimaryKeyConstraint('cartId', 'productId')
    )
    op.create_table('invoices',
    sa.Column('invoiceId', sa.String(), nullable=False),
    sa.Column('orderId', sa.String(), nullable=True),
    sa.Column('invoiceAmount', sa.Integer(), nullable=False),
    sa.Column('paymentDate', sa.DateTime(), nullable=True),
    sa.Column('pdfUrl', sa.String(length=255), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.PrimaryKeyConstraint('invoiceId'),
    sa.UniqueConstraint('orderId')
    )
    op.create_table('ordersProducts',
    sa.Column('orderId', sa.String(), nullable=False),
    sa.Column('productId', sa.String(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('productAmount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.ForeignKeyConstraint(['productId'], ['products.productId'], ),
    sa.PrimaryKeyConstraint('orderId', 'productId')
    )
    op.create_table('routesOrders',
    sa.Column('routeId', sa.String(), nullable=False),
    sa.Column('orderId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.ForeignKeyConstraint(['routeId'], ['routes.routeId'], ),
    sa.PrimaryKeyConstraint('routeId', 'orderId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routesOrders')
    op.drop_table('ordersProducts')
    op.drop_table('invoices')
    op.drop_table('cartsProducts')
    op.drop_table('productHistory')
    op.drop_table('otp')
    op.drop_index(op.f('ix_orders_orderDate'), table_name='orders')
    op.drop_index(op.f('ix_orders_customerReference'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('customerHistory')
    op.drop_table('carts')
    op.drop_table('site_configs')
    op.drop_table('resourceActions')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('permissions')
    op.drop_table('enabled_modules')
    op.drop_index(op.f('ix_employees_lastName'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_lastName'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customerReference'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('tenant_data')
    op.drop_table('routes')
    op.drop_table('roles')
    op.drop_table('resources')
    op.drop_table('modules')
    op.drop_table('categories')
    op.drop_index(op.f('ix_addresses_postCode'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('actions')
    # ### end Alembic commands ###
